# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Animal' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Realm'
  # Pods for Animal

  target 'AnimalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
